# -*- coding: utf-8 -*-
"""DL Microscopy Challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L3ZbJe3pk6XM8zsPnHdQZ-RIwiCv5F-o
"""

import numpy as np
import matplotlib.pyplot as plt
from skimage.transform import resize

# Download the dataset

from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# View example digit
plt.imshow(x_train[50])

# Resize the example digit to 14 x 14
low_res = resize(x_train[50], (14, 14), anti_aliasing=True)

# View low resolution example image
plt.imshow(low_res)

# Resize all training images to 14 x 14
x_train_lowres = resize(x_train, (x_train.shape[0], 14, 14), anti_aliasing=True)

# Resize all test images to 14 x 14
x_test_lowres = resize(x_test, (x_test.shape[0], 14, 14), anti_aliasing=True)

# View the dataset
index = np.random.randint(0,x_train.shape[0])
f, axarr = plt.subplots(1,2)
axarr[0].imshow(x_train_lowres[index])
axarr[1].imshow(x_train[index])
print(y_train[index])

# Build a neural network
# That takes low resolution images (14 x 14)
# Outputs high resolution images (28 x 28)